### ISSUE TITLE
Location of Mono bin dir changed in Unity 5.4 - compiler fails

### ISSUE THREAD

**Issue by tonysheeder** [daterre/Cradle#21]
I'm receiving the the following exception message when I publish a (very simple) test story (Harlowe) from Twine into Unity:

SystemException: Error running gmcs: Cannot find the specified file
Mono.CSharp.CSharpCodeCompiler.CompileFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames)
Mono.CSharp.CSharpCodeCompiler.CompileFromSourceBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] sources)
Mono.CSharp.CSharpCodeCompiler.CompileAssemblyFromSourceBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] sources)
System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromSource (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames)
Cradle.Editor.CradleAssetProcessor.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at /Users/daterre/Projects/UnityTwine/unity/UnityTwine/Assets/Cradle/.src/Cradle.Editor/Editor/CradleAssetProcessor.cs:146)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, 

The story does open properly in a browser. Solution?

**Comment by daterre** [comment]
Thanks for opening the issue and sorry about that. I have a couple of questions:

1. Are you running it on Mac?
2. Is your Unity installation directory different than the default? (/Applications/Unity)

**Comment by daterre** [comment]
I added a dynamic fix to the Mono path as specified here: https://github.com/AngryAnt/Behave-release/issues/21#issuecomment-219602604

Could you please update your Cradle source and confirm that this is fixed? Thanks!

**Comment by tonysheeder** [comment]
Thanks for the quick response - I am running it on Mac and the Unity installation is the default. I'll update Cradle and let you know what happens. Thx again.

**Comment by tonysheeder** [comment]
I downloaded Cradle again and reimported it into Unity. Still getting the gmcs error, though. Question - is the Mono path fix a change you made or a change I need to make (assuming the former, but maybe I misunderstood)?

**Comment by daterre** [comment]
You are right, you shouldn't have to do anything. There is a bug in Unity on Mac that requires scripts to manually reference the installation directory for certain actions. Before the fix I had the directory path hard-coded, now it uses [EditorApplication.applicationContentsPath](https://docs.unity3d.com/ScriptReference/EditorApplication-applicationContentsPath.html) which should be dynamic. But since it didn't help, maybe that isn't your problem.

If you don't mind, could you please add a script called UnityPathDebug.cs to the Assets/Editor folder in your project and tell me what it says in the console? Thanks!

```c#
using UnityEditor;
using UnityEngine;

[InitializeOnLoad]
public class UnityPathDebug  {

	static UnityPathDebug()
	{
		Debug.Log(UnityEditor.EditorApplication.applicationContentsPath);
	}
}
```

**Comment by tonysheeder** [comment]
I got this: 
Assets/UnityTestTools/IntegrationTestsFramework/TestRunner/Editor/PlatformRunner/PlatformRunner.cs(112,39): warning CS0618: `UnityEditor.BuildTargetGroup.WebPlayer' is obsolete: `WebPlayer was removed in 5.4, consider using WebGL'

**Comment by daterre** [comment]
I see you're using 5.4, I haven't yet tested on Unity 5.4, so that might be an issue. This message is unrelated to Cradle though. Wasn't there any other message? Sorry if I wasn't clear, what I meant was to create a script with the contents I posted above and put it in the Assets/Editor folder. This should print the path to your installation directory in the console and will help me understand why the error is happening.

**Comment by tonysheeder** [comment]
I redid everything and got this:
/Applications/Unity/Unity.app/Contents
UnityEngine.Debug:Log(Object)
UnityPathDebug:.cctor() (at Assets/Editor/UnityPathDebug.cs:9)
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

**Comment by daterre** [comment]
Thanks! I'm going to test on 5.4 Mac and will update you.

**Comment by daterre** [comment]
I can confirm that Cradle is broken in Unity 5.4 on Mac because Unity changed the location of their DLLs. I am making a fix for this.

**Comment by daterre** [comment]
Done -- added options for both 5.4 and 5.3>

**Comment by tonysheeder** [comment]
Thank you for the update

**Comment by mlagache** [comment]
Hi. We still have the problem, even if we update the craddle dlls :(
We have hardcoded paths to /Users/Documents/Daterre/...
We also have tried those solutions : https://github.com/AngryAnt/Behave-release/issues/21

**Comment by daterre** [comment]
Sorry I didn't answer your comment from 4 days ago. Let's continue tackling this issue here.

**Comment by mlagache** [comment]
Version : 5.4.0f3 Personal
Path : Applications/Unity/Unity.app/

**Comment by daterre** [comment]
I'm sorry about the troubles, please bear with me. Could you please do the following:

1. Go to /Applications/Unity/Unity.app
2. Right click -> Show package contents
3. Look for the file 'gmcs' in Contents/Frameworks/Mono/bin or Contents/Mono/bin. If it isn't there, try to find it somewhere in the Contents folder and let me know if/where you find it.

Your help greatly appreciated.

**Comment by mlagache** [comment]
There's actually nothing on my client folder (Unity > Contents > Frameworks > Mono > Bin)
Don't even know how it is possible...

And could'nt find gmcs elsewhere...

Any hint ?

Thx !

**Comment by daterre** [comment]
Very strange. Are you sure it's not hidden? I'm pretty sure Unity won't run properly if gmcs isn't available - they use it to compile all game scripts.

**Comment by mlagache** [comment]
Yeah we checked hidden files...
GOnna ask him to re install everything maybe ?
I know for sure we did try to install older versions of mono (standalone stuff). Maybe something went wrong during installation...

**Comment by daterre** [comment]
It's possible that might be related. Maybe it got uninstalled or deleted somehow along with a Mono standalone uninstall? I mean, it's unlikely but I can't imagine how else it could have disappeared.

**Comment by mlagache** [comment]
Sorry for bothering, everything is set back to normal after re installing Unity.
Strange though....

Thank you very much !

**Comment by daterre** [comment]
Great! Good to know Mono installations can mess with stuff like that.
